{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <pytest_allure_feature_story.TestLogin object at 0x0000020CEF991970>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failure(self):\n        with allure.step(\"点击用户名\"):\n            print(\"请输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"请输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert \"1\"==1\nE           AssertionError: assert '1' == 1\n\npytest_allure_feature_story.py:29: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1627295779691, "stop": 1627295779691}, {"name": "点击密码", "status": "passed", "start": 1627295779691, "stop": 1627295779691}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"C:\\Users\\邱州炫\\Desktop\\study\\pytest_allure_feature_story.py\", line 29, in test_login_failure\n    assert \"1\"==1\n"}, "start": 1627295779691, "stop": 1627295779691}], "attachments": [{"name": "stdout", "source": "de903380-7fa3-45a4-8a8d-991d75925606-attachment.txt", "type": "text/plain"}], "start": 1627295779691, "stop": 1627295779692, "uuid": "188a9fd3-de26-41b2-a0d8-fcb32710052a", "historyId": "1b6e89d0ff6681658cd46a938597e23f", "testCaseId": "3f655696a08b6ac0521bccb03de22243", "fullName": "pytest_allure_feature_story.TestLogin#test_login_failure", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "密码缺失"}, {"name": "suite", "value": "pytest_allure_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-V2RHK3K3"}, {"name": "thread", "value": "32456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_allure_feature_story"}]}